Repository Alfresco/acs-community-packaging, pull requests merged in 2021-07, with the labels that each got.

#1412 Use LF for Dockerfile(s) and .sh scripts (.gitattributes) [skip ci]
  .gitattributes
Labels: PR: partially-approved

#1416 bump-share-7.0.1
  pom.xml
Labels: PR: unreviewed

#1417 SEARCH-2878 Update the supported SearchService version
  tests/environment/.env
Labels: PR: reviewed-approved

#1421 SEARCH-2878 Update the supported for SearchService to 2.0.2
  tests/environment/.env
Labels: PR: unreviewed

#1424 ACS-1822 ACS 7.1 Supported Platforms: PostgreSQL 13.3
  dev/docker-compose.yml
  tests/environment/.env
Labels: PR: reviewed-approved
