Repository Alfresco/acs-community-packaging, pull requests merged in 2021-02, with the labels that each got.

#1243 ACS-1185 Update activemq images to 5.16.1
  dev/docker-compose.yml
  tests/environment/.env
Labels: PR: partially-approved

#1244 bump of share 7.0.0-A16
  pom.xml
Labels: PR: unreviewed

#1247 feature/APPS-release: [release] share A17
  pom.xml
Labels: PR: partially-approved

#1248 ATS-862 2.3.8 T-Engines
  dev/docker-compose.yml
  tests/environment/.env
Labels: PR: unreviewed

#1251 ACS-1265 Update ActiveMQ broker URLs to use NIO
  tests/environment/docker-compose-minimal+transforms.yml
  tests/environment/docker-compose-minimal.yml
Labels: PR: reviewed-approved

#1252 ACS-1110 replace fabric8 with docker-maven-plugin
  distribution/pom.xml
  docker-alfresco/pom.xml
Labels: PR: unreviewed

#1256 ACS-1183 ACS 7 Stacks: PostgreSQL
  .gitbugtraq
  dev/docker-compose.yml
  tests/environment/.env
Labels: PR: unreviewed

#1253 feature/APPS-release-share: update share to A18 in acs-community-packaging
  pom.xml
Labels: PR: partially-approved

#1260 Update the ACS build scripts
  scripts/travis/build_functions.sh
Labels: PR: reviewed-approved

#1261 Bump of Share A19
  pom.xml
Labels: PR: partially-approved
