Repository Alfresco/acs-community-packaging, pull requests merged in 2021-06, with the labels that each got.

#1358 ACS-1611 Add AGS to acs-community-packagingFeature/ags reorg
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  dev/README.md
  dev/aliases
  dev/dev-acs-amps-overlay/pom.xml
  dev/dev-repo-amps-overlay/pom.xml
  dev/dev-share-amps-overlay/pom.xml
  dev/dev-tomcat/pom.xml
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j.properties
  dev/docker-compose.yml
  dev/pom.xml
  distribution/src/assembly/distribution.xml
  distribution/src/main/resources/README.txt
  docker-alfresco/pom.xml
  pom.xml
  public-javadoc/pom.xml
  scripts/travis/build.sh
  scripts/travis/init.sh
  scripts/travis/maven_release.sh
Labels: PR: unreviewed

#1374 APPS-1028 Build&publish an AGS distribution zip during the ACS release
  .travis.yml
  distribution-ags/pom.xml
  distribution-ags/src/assemble/ags-distribution.xml
  pom.xml
  scripts/travis/copy_ags_to_release_bucket.sh
Labels: PR: partially-approved

#1390 ACS-1709 Include Share's Google AMP in the tomcat dev env
  dev/dev-share-amps-overlay/pom.xml
Labels: PR: reviewed-approved

#1389 ACS-1710 Let repo developers build the project without having to build AGS first.
  dev/aliases
  pom.xml
  scripts/travis/build.sh
  scripts/travis/maven_release.sh
Labels: PR: reviewed-approved

#1400 bump-share-7.0.1-A4
  pom.xml
Labels: PR: partially-approved
